#ifndef RC3D_EDIT_H
#define RC3D_EDIT_H

#include <stdint.h>


//// EDITOR DEFAULTS
#define ED_DEFAULT_WALL_UPPER_TEX_ID        1   // brick (though should be "no texture")
#define ED_DEFAULT_WALL_MED_TEX_ID          1
#define ED_DEFAULT_WALL_LOWER_TEX_ID        1
#define ED_DEFAULT_SECTOR_FLOOR_TEX_ID      3
#define ED_DEFAULT_SECTOR_CEILING_TEX_ID    255


#define RC3D_SECTOR_STATE_NONE           0u
#define RC3D_SECTOR_STATE_RAISE_FLOOR    0x01u
#define RC3D_SECTOR_STATE_LOWER_FLOOR    0x02u
#define RC3D_SECTOR_STATE_LOWER_CEILING  0x04u
#define RC3D_SECTOR_STATE_RAISE_CEILING  0x08u


// colours 

// colour settings
#define ED_INSPECTOR_TITLE_COL  7
#define ED_INSPECTOR_TEXT_COL   2
#define ED_TEXT_COL             6

#define ED_START_COL            2   // white
#define ED_HOME_GRID_COL        1

#define ED_GRID_MAJOR_COL       3  // blue
#define ED_GRID_MINOR_COL       5  // darker blue
#define ED_GRID_MICRO_COL       5

//#define ED_VERT_COL              3
//#define ED_WALL_COL              2
#define ED_PORTAL_COL            8  // green


#define ED_COLOUR_SCROLL_BAR_BG 5
#define ED_COLOUR_SCROLL_BAR    3
#define ED_COLOUR_SCROLL_BAR_FRAME  1

#define ED_UI_BG                5
#define ED_UI_BORDER            2

#define ED_COLOUR_SELECTED_SECTOR   7  // yellow



#define ED_CURSOR_COL           11

#define ED_COLOUR_BTN_TEXT              2
#define ED_COLOUR_BTN_BG                9
#define ED_COLOUR_BTN_BG_ACTIVE         8
#define ED_COLOUR_BTN_FRAME             1
#define ED_COLOUR_BTN_TXT_DISABLED      15
#define ED_COLOUR_BTN_BG_DISABLED       1
#define ED_COLOUR_BTN_FRAME_DISABLED    15
#define ED_COLOUR_BTN_ACTIVE            6
#define ED_COLOUR_BTN_TEXT_HOVER        16


#define ED_COLOUR_TOOLTIP_BG        15
#define ED_COLOUR_TOOLTIP_BORDER    14
#define ED_COLOUR_TOOLTIP_TEXT      7

#define ED_COLOUR_TEXT_BAR_BG       4
#define ED_COLOUR_TEXT_BAR_BORDER   3

#define ED_OBJECT_TEXT_NOTE_BG      16
#define ED_OBJECT_TEXT_NOTE_BORDER  4
#define ED_OBJECT_TEXT_TEXT         3

// map validator
#define ED_VALIDATOR_TEXT                   2
#define ED_VALIDATOR_SELECTION_BG           3
#define ED_VALIDATOR_SELECTION_TEXT         14

// expanded panels
#define ED_EXPANDED_MENU_TEXT               2

// inspectors
#define ED_INSPECTOR_PANELS_HEADER_TEXT     7
#define ED_INSPECTOR_PARENT_PANELS_BG       16
#define ED_INSPECTOR_PARENT_PANELS_FRAME    6
#define ED_INSPECTOR_PANELS_BACKPANEL       17
#define ED_INSPECTOR_PANELS_PANELFRAME      3

// texture explorer
#define ED_TEXTURE_EXPLORER_HEADER_TEXT     2
#define ED_TEXTURE_EXPLORER_SELECT_FRAME    8

// DRAFTING colours
// walls
#define ED_COLOUR_DRAFTWALL         11
#define ED_COLOUR_HOVER_WALL        1
#define ED_COLOUR_SELECTED_WALL     8  
#define ED_COLOUR_WALL              26//11
#define ED_COLOUR_WALLO             8
#define ED_COLOUR_WALL_SPECIAL      14

// vertex
#define ED_COLOUR_VERTEX            11
#define ED_COLOUR_VERTEX_HOVER      10
#define ED_COLOUR_VERTEX_SELECTED   2

#define ED_COLOUR_VERTEX_SPLIT_PREV 7
#define ED_COLOUR_MULTI_SELECT_RANGE_BOX    1


#define RC3D_SECTOR_FLAGS_FLICKERING_LIGHTS 0x100
#define RC3D_SECTOR_FLAGS_PULSATING_LIGHT   0x200
#define RC3D_SECTOR_FLAGS_FULLBRIGHT        0x400







// buttons 

enum
{
    GUI_BTN_UNDO = 100,
    GUI_BTN_REDO,
    GUI_BTN_QUIT,
    GUI_BTN_HELP,
    GUI_BTN_NEWMAP,
    GUI_BTN_LOAD,
    GUI_BTN_SAVE,
    GUI_BTN_EXPORT,
    GUI_BTN_GRID,
    GUI_BTN_FINISH,
    GUI_BTN_CLRDRAFT,
    GUI_BTN_VALIDATOR,
    GUI_BTN_SHOWTEXTURE_BROWSER,

    GUI_BTN_PLAYER_START_ANGLE_MINUS,
    GUI_BTN_PLAYER_START_ANGLE_PLUS,

    GUI_BTN_WALL_SOLID,
    GUI_BTN_WALL_PORTAL,
    GUI_BTN_WALL_WINDOW,
    GUI_BTN_WALL_DOOR,
    GUI_BTN_WALL_TRANSPARENCY,
    GUI_BTN_WALL_FLAG_DOUBLESIDED,
    GUI_BTN_WALL_FLAG_CLICKABLE,
    GUI_BTN_WALL_FLAG_OBJ_ACT_ENTER,
    GUI_BTN_WALL_FLAG_OBJ_ACT_EXIT,
    GUI_BTN_WALL_OBJ_ID_MINUS,
    GUI_BTN_WALL_OBJ_ID_PLUS,

    GUI_BTN_WALL_SPLIT,

    GUI_BTN_WALL_CLAMP_XL,
    GUI_BTN_WALL_CLAMP_XR,
    GUI_BTN_WALL_FLIP_X,
    GUI_BTN_WALL_CLAMP_YT,
    GUI_BTN_WALL_CLAMP_YB,
    GUI_BTN_WALL_FLIP_Y,
    GUI_BTN_WALL_TEXTURE_X_OFFSET_MINUS,
    GUI_BTN_WALL_TEXTURE_X_OFFSET_PLUS,
    GUI_BTN_WALL_TEXTURE_Y_OFFSET_MINUS,
    GUI_BTN_WALL_TEXTURE_Y_OFFSET_PLUS,

    GUI_BTN_WALL_COPY_PROPS,
    GUI_BTN_WALL_PASTE_PROPS,
    GUI_BTN_WALL_OPENBOT_MINUS,
    GUI_BTN_WALL_OPENBOT_PLUS,
    GUI_BTN_WALL_OPENTOP_MINUS,
    GUI_BTN_WALL_OPENTOP_PLUS,
    GUI_BTN_WALL_TEX_SX_MINUS,
    GUI_BTN_WALL_TEX_SX_PLUS,
    GUI_BTN_WALL_TEX_SY_MINUS,
    GUI_BTN_WALL_TEX_SY_PLUS,
    GUI_BTN_WALL_TEX_ROT_MINUS,
    GUI_BTN_WALL_TEX_ROT_PLUS,
    GUI_BTN_WALL_TEX_ROT_RESET,
    GUI_BTN_WALL_TEX_BRIGHT_MINUS,
    GUI_BTN_WALL_TEX_BRIGHT_PLUS,

    GUI_BTN_WALL_QUICK_TEXTURE,

    
    GUI_BTN_SECTOR_FLOOR_MINUS,
    GUI_BTN_SECTOR_FLOOR_PLUS,
    GUI_BTN_SECTOR_CEIL_MINUS,
    GUI_BTN_SECTOR_CEIL_PLUS,
    GUI_BTN_SECTOR_GLOW_MINUS,
    GUI_BTN_SECTOR_GLOW_PLUS,
    GUI_BTN_SECTOR_TAG_MINUS,
    GUI_BTN_SECTOR_TAG_PLUS,
    GUI_BTN_SECTOR_STATE_MINUS,
    GUI_BTN_SECTOR_STATE_PLUS,
    GUI_BTN_SECTOR_FLOOR_MIN_MINUS,
    GUI_BTN_SECTOR_FLOOR_MIN_PLUS,
    GUI_BTN_SECTOR_FLOOR_MAX_MINUS,
    GUI_BTN_SECTOR_FLOOR_MAX_PLUS,
    GUI_BTN_SECTOR_CEIL_MIN_MINUS,
    GUI_BTN_SECTOR_CEIL_MIN_PLUS,
    GUI_BTN_SECTOR_CEIL_MAX_MINUS,
    GUI_BTN_SECTOR_CEIL_MAX_PLUS,
    GUI_BTN_SECTOR_FLOOR_FLOW_MINUS,
    GUI_BTN_SECTOR_FLOOR_FLOW_PLUS,
    GUI_BTN_SECTOR_CEIL_FLOW_MINUS,
    GUI_BTN_SECTOR_CEIL_FLOW_PLUS,
    GUI_BTN_SECTOR_COPY_PROPS,
    GUI_BTN_SECTOR_PASTE_PROPS,
    GUI_BTN_SECTOR_CLAMP_X1,
    GUI_BTN_SECTOR_CLAMP_X2,
    GUI_BTN_SECTOR_CLAMP_Y1,
    GUI_BTN_SECTOR_CLAMP_Y2,

    GUI_BTN_SECTOR_FLAGS_BIT0,  ///// 0-7 BITS //////////////
    GUI_BTN_SECTOR_FLAGS_BIT1,
    GUI_BTN_SECTOR_FLAGS_BIT2,
    GUI_BTN_SECTOR_FLAGS_BIT3,
    GUI_BTN_SECTOR_FLAGS_BIT4,
    GUI_BTN_SECTOR_FLAGS_BIT5,
    GUI_BTN_SECTOR_FLAGS_BIT6,
    GUI_BTN_SECTOR_FLAGS_BIT7,
    GUI_BTN_SECTOR_FLAGS_BIT8,  ///// 8-15 BITS /////////////
    GUI_BTN_SECTOR_FLAGS_BIT9,
    GUI_BTN_SECTOR_FLAGS_BIT10,
    GUI_BTN_SECTOR_FLAGS_BIT11,
    GUI_BTN_SECTOR_FLAGS_BIT12,
    GUI_BTN_SECTOR_FLAGS_BIT13,
    GUI_BTN_SECTOR_FLAGS_BIT14,
    GUI_BTN_SECTOR_FLAGS_BIT15,



    GUI_BTN_OBJECT_TAGID_PLUS,
    GUI_BTN_OBJECT_TAGID_MINUS,
    GUI_BTN_OBJECT_TYPE_PLUS,
    GUI_BTN_OBJECT_TYPE_MINUS,
    GUI_BTN_OBJECT_TARGETTAGID_PLUS,
    GUI_BTN_OBJECT_TARGETTAGID_MINUS,
    GUI_BTN_OBJECT_RADIUS_PLUS,
    GUI_BTN_OBJECT_RADIUS_MINUS,
    GUI_BTN_OBJECT_ANGLE_PLUS,
    GUI_BTN_OBJECT_ANGLE_MINUS,
    GUI_BTN_OBJECT_ZAXIS_PLUS,
    GUI_BTN_OBJECT_ZAXIS_MINUS,
    GUI_BTN_OBJECT_TSCALEX_MINUS,
    GUI_BTN_OBJECT_TSCALEX_PLUS,
    GUI_BTN_OBJECT_TSCALEY_MINUS,
    GUI_BTN_OBJECT_TSCALEY_PLUS,
    GUI_BTN_OBJECT_GET_ZAXIS,
    GUI_BTN_OBJECT_BAKE_ROUTE,
    GUI_BTN_OBJECT_CLEAR_BAKED_ROUTE,
    GUI_BTN_OBJECT_LABELS_VISIBLE,

    GUI_BTN_OBJECT_FLAGS_bit0, 
    GUI_BTN_OBJECT_FLAGS_bit1, 
    GUI_BTN_OBJECT_FLAGS_bit2, 
    GUI_BTN_OBJECT_FLAGS_bit3, 
    GUI_BTN_OBJECT_FLAGS_bit4, 
    GUI_BTN_OBJECT_FLAGS_bit5, 
    GUI_BTN_OBJECT_FLAGS_bit6, 
    GUI_BTN_OBJECT_FLAGS_bit7, 

    GUI_BTN_OBJECT_INFLAGS_bit0,
    GUI_BTN_OBJECT_INFLAGS_bit1,
    GUI_BTN_OBJECT_INFLAGS_bit2,
    GUI_BTN_OBJECT_INFLAGS_bit3,
    GUI_BTN_OBJECT_INFLAGS_bit4,
    GUI_BTN_OBJECT_INFLAGS_bit5,
    GUI_BTN_OBJECT_INFLAGS_bit6,
    GUI_BTN_OBJECT_INFLAGS_bit7,

    GUI_BTN_OBJECT_OUTFLAGS_bit0,
    GUI_BTN_OBJECT_OUTFLAGS_bit1,
    GUI_BTN_OBJECT_OUTFLAGS_bit2,
    GUI_BTN_OBJECT_OUTFLAGS_bit3,
    GUI_BTN_OBJECT_OUTFLAGS_bit4,
    GUI_BTN_OBJECT_OUTFLAGS_bit5,
    GUI_BTN_OBJECT_OUTFLAGS_bit6,
    GUI_BTN_OBJECT_OUTFLAGS_bit7,



    GUI_BTN_CONFIRM_YES,
    GUI_BTN_CONFIRM_NO,

    GUI_BTN_SECTOR_CUTTER,      // F6
    GUI_BTN_REPAIR_TOPOLOGY,    // F7
    GUI_BTN_CLEANMAP,           // F8
    GUI_BTN_MAPVALIDATOR,       // F9
    GUI_BTN_LAUNCH_TEST_MAP,    // F12


    GUI_BTN_SECTOR_FTEX_SX_MINUS,
    GUI_BTN_SECTOR_FTEX_SX_PLUS,
    GUI_BTN_SECTOR_FTEX_SY_MINUS,
    GUI_BTN_SECTOR_FTEX_SY_PLUS,
    GUI_BTN_SECTOR_FTEX_ROT_MINUS,
    GUI_BTN_SECTOR_FTEX_ROT_PLUS,
    GUI_BTN_SECTOR_FTEX_ROT_RESET,

    GUI_BTN_SECTOR_CTEX_SX_MINUS,
    GUI_BTN_SECTOR_CTEX_SX_PLUS,
    GUI_BTN_SECTOR_CTEX_SY_MINUS,
    GUI_BTN_SECTOR_CTEX_SY_PLUS,
    GUI_BTN_SECTOR_CTEX_ROT_MINUS,
    GUI_BTN_SECTOR_CTEX_ROT_PLUS,
    GUI_BTN_SECTOR_CTEX_ROT_RESET,
};





















void rc3dEditInit(void);
void rc3dEditUpdate(float dt,
                    const uint8_t *keys,
                    int mouseX,
                    int mouseY,
                    uint32_t mouseButtons,
                    int mouseWheelY);
int rc3dEditHandleTextInput(const char *text);


void rc3dEditRender(void);
void rc3dGuiDirty(void);
int rc3dGuiCheckDirty();

#endif
